# Generated by Django 5.0.3 on 2024-03-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='st_subject',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
